//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.07.29 at 03:04:53 PM BRT 
//


package org.alfredlibrary.gov.comprasnet.catalogo.materiais.retorno;

import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.alfredlibrary.gov.comprasnet.catalogo.materiais.retorno package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _UnidadeFornecimento_QNAME = new QName("", "unidade_fornecimento");
    private final static QName _Grupo_QNAME = new QName("", "grupo");
    private final static QName _SiglaUnidadeFornecimento_QNAME = new QName("", "sigla_unidade_fornecimento");
    private final static QName _Erroxml_QNAME = new QName("", "erroxml");
    private final static QName _Classe_QNAME = new QName("", "classe");
    private final static QName _DescricaoPDM_QNAME = new QName("", "descricaoPDM");
    private final static QName _CodigoPDM_QNAME = new QName("", "codigoPDM");
    private final static QName _Descricao_QNAME = new QName("", "descricao");
    private final static QName _Codigo_QNAME = new QName("", "codigo");
    private final static QName _Sustentabilidade_QNAME = new QName("", "sustentabilidade");
    private final static QName _Erronat_QNAME = new QName("", "erronat");
    private final static QName _UnidadeMedida_QNAME = new QName("", "unidade_medida");
    private final static QName _Capacidade_QNAME = new QName("", "capacidade");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.alfredlibrary.gov.comprasnet.catalogo.materiais.retorno
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Descxml }
     * 
     */
    public Descxml createDescxml() {
        return new Descxml();
    }

    /**
     * Create an instance of {@link Unidade }
     * 
     */
    public Unidade createUnidade() {
        return new Unidade();
    }

    /**
     * Create an instance of {@link Itens }
     * 
     */
    public Itens createItens() {
        return new Itens();
    }

    /**
     * Create an instance of {@link Unidades }
     * 
     */
    public Unidades createUnidades() {
        return new Unidades();
    }

    /**
     * Create an instance of {@link Descnat }
     * 
     */
    public Descnat createDescnat() {
        return new Descnat();
    }

    /**
     * Create an instance of {@link Item }
     * 
     */
    public Item createItem() {
        return new Item();
    }

    /**
     * Create an instance of {@link Cnet }
     * 
     */
    public Cnet createCnet() {
        return new Cnet();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "unidade_fornecimento")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createUnidadeFornecimento(String value) {
        return new JAXBElement<String>(_UnidadeFornecimento_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "grupo")
    public JAXBElement<BigInteger> createGrupo(BigInteger value) {
        return new JAXBElement<BigInteger>(_Grupo_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "sigla_unidade_fornecimento")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createSiglaUnidadeFornecimento(String value) {
        return new JAXBElement<String>(_SiglaUnidadeFornecimento_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "erroxml")
    public JAXBElement<BigInteger> createErroxml(BigInteger value) {
        return new JAXBElement<BigInteger>(_Erroxml_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "classe")
    public JAXBElement<BigInteger> createClasse(BigInteger value) {
        return new JAXBElement<BigInteger>(_Classe_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "descricaoPDM")
    public JAXBElement<String> createDescricaoPDM(String value) {
        return new JAXBElement<String>(_DescricaoPDM_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "codigoPDM")
    public JAXBElement<BigInteger> createCodigoPDM(BigInteger value) {
        return new JAXBElement<BigInteger>(_CodigoPDM_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "descricao")
    public JAXBElement<String> createDescricao(String value) {
        return new JAXBElement<String>(_Descricao_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "codigo")
    public JAXBElement<BigInteger> createCodigo(BigInteger value) {
        return new JAXBElement<BigInteger>(_Codigo_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "sustentabilidade")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createSustentabilidade(String value) {
        return new JAXBElement<String>(_Sustentabilidade_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "erronat")
    public JAXBElement<BigInteger> createErronat(BigInteger value) {
        return new JAXBElement<BigInteger>(_Erronat_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "unidade_medida")
    public JAXBElement<String> createUnidadeMedida(String value) {
        return new JAXBElement<String>(_UnidadeMedida_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "capacidade")
    public JAXBElement<String> createCapacidade(String value) {
        return new JAXBElement<String>(_Capacidade_QNAME, String.class, null, value);
    }

}
