//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.07.29 at 03:04:53 PM BRT 
//


package org.alfredlibrary.gov.comprasnet.catalogo.materiais.retorno;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}unidade_fornecimento"/>
 *         &lt;element ref="{}sigla_unidade_fornecimento"/>
 *         &lt;element ref="{}capacidade"/>
 *         &lt;element ref="{}unidade_medida"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "unidadeFornecimento",
    "siglaUnidadeFornecimento",
    "capacidade",
    "unidadeMedida"
})
@XmlRootElement(name = "unidade")
public class Unidade {

    @XmlElement(name = "unidade_fornecimento", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String unidadeFornecimento;
    @XmlElement(name = "sigla_unidade_fornecimento", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String siglaUnidadeFornecimento;
    @XmlElement(required = true)
    protected String capacidade;
    @XmlElement(name = "unidade_medida", required = true)
    protected String unidadeMedida;

    /**
     * Gets the value of the unidadeFornecimento property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnidadeFornecimento() {
        return unidadeFornecimento;
    }

    /**
     * Sets the value of the unidadeFornecimento property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnidadeFornecimento(String value) {
        this.unidadeFornecimento = value;
    }

    /**
     * Gets the value of the siglaUnidadeFornecimento property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSiglaUnidadeFornecimento() {
        return siglaUnidadeFornecimento;
    }

    /**
     * Sets the value of the siglaUnidadeFornecimento property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSiglaUnidadeFornecimento(String value) {
        this.siglaUnidadeFornecimento = value;
    }

    /**
     * Gets the value of the capacidade property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCapacidade() {
        return capacidade;
    }

    /**
     * Sets the value of the capacidade property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCapacidade(String value) {
        this.capacidade = value;
    }

    /**
     * Gets the value of the unidadeMedida property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnidadeMedida() {
        return unidadeMedida;
    }

    /**
     * Sets the value of the unidadeMedida property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnidadeMedida(String value) {
        this.unidadeMedida = value;
    }

}
