//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.07.28 at 04:08:51 PM BRT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "cnet_consultamatserv", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.alfredlibrary.gov.comprasnet.catalogo.materiais.consulta;
