//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.07.29 at 03:04:53 PM BRT 
//


package org.alfredlibrary.gov.comprasnet.catalogo.materiais.retorno;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}erroxml"/>
 *         &lt;element ref="{}descxml"/>
 *         &lt;element ref="{}erronat"/>
 *         &lt;element ref="{}descnat"/>
 *         &lt;element ref="{}itens"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "erroxml",
    "descxml",
    "erronat",
    "descnat",
    "itens"
})
@XmlRootElement(name = "cnet")
public class Cnet {

    @XmlElement(required = true)
    protected BigInteger erroxml;
    @XmlElement(required = true)
    protected Descxml descxml;
    @XmlElement(required = true)
    protected BigInteger erronat;
    @XmlElement(required = true)
    protected Descnat descnat;
    @XmlElement(required = true)
    protected Itens itens;

    /**
     * Gets the value of the erroxml property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getErroxml() {
        return erroxml;
    }

    /**
     * Sets the value of the erroxml property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setErroxml(BigInteger value) {
        this.erroxml = value;
    }

    /**
     * Gets the value of the descxml property.
     * 
     * @return
     *     possible object is
     *     {@link Descxml }
     *     
     */
    public Descxml getDescxml() {
        return descxml;
    }

    /**
     * Sets the value of the descxml property.
     * 
     * @param value
     *     allowed object is
     *     {@link Descxml }
     *     
     */
    public void setDescxml(Descxml value) {
        this.descxml = value;
    }

    /**
     * Gets the value of the erronat property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getErronat() {
        return erronat;
    }

    /**
     * Sets the value of the erronat property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setErronat(BigInteger value) {
        this.erronat = value;
    }

    /**
     * Gets the value of the descnat property.
     * 
     * @return
     *     possible object is
     *     {@link Descnat }
     *     
     */
    public Descnat getDescnat() {
        return descnat;
    }

    /**
     * Sets the value of the descnat property.
     * 
     * @param value
     *     allowed object is
     *     {@link Descnat }
     *     
     */
    public void setDescnat(Descnat value) {
        this.descnat = value;
    }

    /**
     * Gets the value of the itens property.
     * 
     * @return
     *     possible object is
     *     {@link Itens }
     *     
     */
    public Itens getItens() {
        return itens;
    }

    /**
     * Sets the value of the itens property.
     * 
     * @param value
     *     allowed object is
     *     {@link Itens }
     *     
     */
    public void setItens(Itens value) {
        this.itens = value;
    }

}
