//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.07.29 at 03:04:53 PM BRT 
//


package org.alfredlibrary.gov.comprasnet.catalogo.materiais.retorno;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}codigo"/>
 *         &lt;element ref="{}descricao"/>
 *         &lt;element ref="{}grupo"/>
 *         &lt;element ref="{}classe"/>
 *         &lt;element ref="{}sustentabilidade"/>
 *         &lt;element ref="{}codigoPDM"/>
 *         &lt;element ref="{}descricaoPDM"/>
 *         &lt;element ref="{}unidades"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "codigo",
    "descricao",
    "grupo",
    "classe",
    "sustentabilidade",
    "codigoPDM",
    "descricaoPDM",
    "unidades"
})
@XmlRootElement(name = "item")
public class Item {

    @XmlElement(required = true)
    protected BigInteger codigo;
    @XmlElement(required = true)
    protected String descricao;
    @XmlElement(required = true)
    protected BigInteger grupo;
    @XmlElement(required = true)
    protected BigInteger classe;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String sustentabilidade;
    @XmlElement(required = true)
    protected BigInteger codigoPDM;
    @XmlElement(required = true)
    protected String descricaoPDM;
    @XmlElement(required = true)
    protected Unidades unidades;

    /**
     * Gets the value of the codigo property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCodigo() {
        return codigo;
    }

    /**
     * Sets the value of the codigo property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCodigo(BigInteger value) {
        this.codigo = value;
    }

    /**
     * Gets the value of the descricao property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescricao() {
        return descricao;
    }

    /**
     * Sets the value of the descricao property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescricao(String value) {
        this.descricao = value;
    }

    /**
     * Gets the value of the grupo property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getGrupo() {
        return grupo;
    }

    /**
     * Sets the value of the grupo property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setGrupo(BigInteger value) {
        this.grupo = value;
    }

    /**
     * Gets the value of the classe property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getClasse() {
        return classe;
    }

    /**
     * Sets the value of the classe property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setClasse(BigInteger value) {
        this.classe = value;
    }

    /**
     * Gets the value of the sustentabilidade property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSustentabilidade() {
        return sustentabilidade;
    }

    /**
     * Sets the value of the sustentabilidade property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSustentabilidade(String value) {
        this.sustentabilidade = value;
    }

    /**
     * Gets the value of the codigoPDM property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCodigoPDM() {
        return codigoPDM;
    }

    /**
     * Sets the value of the codigoPDM property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCodigoPDM(BigInteger value) {
        this.codigoPDM = value;
    }

    /**
     * Gets the value of the descricaoPDM property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescricaoPDM() {
        return descricaoPDM;
    }

    /**
     * Sets the value of the descricaoPDM property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescricaoPDM(String value) {
        this.descricaoPDM = value;
    }

    /**
     * Gets the value of the unidades property.
     * 
     * @return
     *     possible object is
     *     {@link Unidades }
     *     
     */
    public Unidades getUnidades() {
        return unidades;
    }

    /**
     * Sets the value of the unidades property.
     * 
     * @param value
     *     allowed object is
     *     {@link Unidades }
     *     
     */
    public void setUnidades(Unidades value) {
        this.unidades = value;
    }

}
